automation of tests using examples
actility/thingpark-iot-flow-js-driver pull request #7
Opened 2021-01-27 18:25 UTC by mostafaibractility

2021-01-28 15:40 UTC, martintheault requested changes

2021-01-28 15:40 UTC, martintheault commented on README.md
> +[
I think we should add the json schema as we've done for `Driver functions`

2021-01-28 15:40 UTC, martintheault commented on README.md
> +**Note:** A downlink example can be used for `decodeDownlink` and `encodeDownlink` functions as they must be bijective.
The json schema will replace this Note

2021-01-28 15:40 UTC, martintheault commented on examples/advanced-driver/errors/driver.errors.json
> +        "toThrow": "Invalid uplink payload: unknown id '3'"
I think we should use `error` instead of `toThrow`

2021-01-28 15:40 UTC, martintheault commented on examples/advanced-driver/examples/others.examples.json
> +          }
I think there is a space that should be removed, it's the same for other example files

2021-01-28 15:40 UTC, martintheault commented on examples/simple-driver/README.md
> +You can use our files `driver-examples.spec.js` and `driver-errors.spec.js` provided in our driver example [here](./examples/simple-driver/test) to test your payload examples and errors to be thrown.
We must add that they don't have anything to change in the file. They just have to respect the folder names

2021-01-28 15:40 UTC, martintheault commented on examples/simple-driver/README.md
> +**Note:** These errors examples will only used for unit tests and will not be stored in our framework.
will `be` used ?

2021-01-28 15:40 UTC, martintheault commented on examples/simple-driver/README.md
> +	  "data":  {
There is no data for an error ? It should be `error`here, no?

2021-01-28 15:40 UTC, martintheault commented on examples/simple-driver/README.md
> +	{
For the examples, the downlink contain the bytes and data, for the error, only one must be present? With an `error`field.

2021-01-28 16:04 UTC, mostafaibractility commented on examples/simple-driver/README.md
> +	  "data":  {
The `data` is used as an input to `encodeDownlink` and `extractPoints` to test the errors to be thrown by these functions.

2021-01-28 16:07 UTC, mostafaibractility commented on examples/simple-driver/README.md
> +	{
yes,
for uplink : if `bytes` presents alongside `error` then we are testing `decodeUplink`, if `data` presents then we are testing `extractPoints`. 
for downlink: if `bytes` presents alongside `error` then we are testing `decodeDownlink`, if `data` presents then we are testing `encodeDownlink`. 
do you suggest something better? like having 4 types or errors examples?

2021-01-28 20:36 UTC, mostafaibractility commented on README.md
> +[
done

2021-01-28 20:36 UTC, mostafaibractility commented on README.md
> +**Note:** A downlink example can be used for `decodeDownlink` and `encodeDownlink` functions as they must be bijective.
done

2021-01-28 20:36 UTC, mostafaibractility commented on examples/advanced-driver/errors/driver.errors.json
> +        "toThrow": "Invalid uplink payload: unknown id '3'"
done

2021-01-28 20:36 UTC, mostafaibractility commented on examples/advanced-driver/examples/others.examples.json
> +          }
done

2021-01-28 20:36 UTC, mostafaibractility commented on examples/simple-driver/README.md
> +You can use our files `driver-examples.spec.js` and `driver-errors.spec.js` provided in our driver example [here](./examples/simple-driver/test) to test your payload examples and errors to be thrown.
done

2021-01-28 20:36 UTC, mostafaibractility commented on examples/simple-driver/README.md
> +**Note:** These errors examples will only used for unit tests and will not be stored in our framework.
fixed

2021-01-28 20:48 UTC, martintheault commented on README.md
> +The uplink example is used  is an object represented by the following json-schema:
it's not a json schema, it's an example. The json schema describes the fields, see the `driver decode uplink` function

2021-01-28 20:48 UTC, martintheault commented on README.md
> +	    }
problem with indentation, you can use an editor to format json correctly and then copy/paste it to github

2021-01-28 20:48 UTC, martintheault commented on README.md
>  		"description":  "...",
indentation is not correct

2021-01-28 20:48 UTC, martintheault commented on README.md
> +## Testing
don't forget to update the menu

2021-01-29 01:05 UTC, mostafaibractility commented on README.md
> +The uplink example is used  is an object represented by the following json-schema:
fixed

2021-01-29 01:05 UTC, mostafaibractility commented on README.md
> +	    }
fixed

2021-01-29 01:05 UTC, mostafaibractility commented on README.md
>  		"description":  "...",
fixed

2021-01-29 01:05 UTC, mostafaibractility commented on README.md
> +## Testing
done

2021-01-29 09:42 UTC, martintheault requested changes

2021-01-29 09:42 UTC, martintheault commented on README.md
> +        "jest": "^24.9.0"
can be updated to "^25.4.0"

2021-01-29 09:42 UTC, martintheault commented on README.md
> +-   `points`: This field is only mandatory in the `uplink` example where there is some values in the field `data` must be extracted as points.
points is not mandatory for uplink

2021-01-29 09:42 UTC, martintheault commented on README.md
> +#### Uplink example
I think we can use the same json schema for both types. It must be indicated in the "points" field description that it's only valid if type is uplink

2021-01-29 09:42 UTC, martintheault commented on README.md
> +        "type": "string",
you can define an enum in json schema

```
"enum": ["uplink", "downlink"]
```

2021-01-29 09:42 UTC, martintheault commented on README.md
> +        "description": "the uplink message time",
if we use the same json schema, you must remove all references to uplink in descriptions

2021-01-29 09:42 UTC, martintheault commented on README.md
> +You can find the full example tests [here](./examples/simple-driver/test).
I think we must rephrase

2021-01-29 12:57 UTC, mostafaibractility commented on README.md
> +You can find the full example tests [here](./examples/simple-driver/test).
done

2021-01-29 12:57 UTC, mostafaibractility commented on README.md
> +        "description": "the uplink message time",
done

2021-01-29 12:57 UTC, mostafaibractility commented on README.md
> +        "type": "string",
done

2021-01-29 12:59 UTC, mostafaibractility commented on README.md
> +#### Uplink example
done

2021-01-29 13:00 UTC, mostafaibractility commented on README.md
> +-   `points`: This field is only mandatory in the `uplink` example where there is some values in the field `data` must be extracted as points.
rephrased

2021-01-29 13:00 UTC, mostafaibractility commented on README.md
> +        "jest": "^24.9.0"
done

2021-01-29 16:58 UTC, martintheault approved these changes

2021-01-30 01:29 UTC, closed without merging